### ISSUE TITLE
Combine methods

### ISSUE THREAD

**Issue by IanaKhitsko** [dmitri-baklan/MIPZ#2]
https://github.com/dmitri-baklan/MIPZ/blob/8dc37de9935fdbd8103a1c08cb635fee6f6148c5/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L21-L23

move the duplicated code to one method

**Comment by dmitri-baklan** [comment]
Duplicate code was removed to a new method "setUpWinnerData"!
