### ISSUE TITLE
Remove one level of indent

### ISSUE THREAD

**Issue by IanaKhitsko** [dmitri-baklan/MIPZ#3]
https://github.com/dmitri-baklan/MIPZ/blob/8dc37de9935fdbd8103a1c08cb635fee6f6148c5/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L19

if(board[i][j] == 0) {
   continue;
}

**Comment by dmitri-baklan** [comment]
Changed to positive condition, removed one level of indent!
