### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [dmitri-baklan/MIPZ#4]
https://github.com/dmitri-baklan/MIPZ/blob/8dc37de9935fdbd8103a1c08cb635fee6f6148c5/RenjuChecker/src/main/java/org/example/util/RenjuInputReader.java#L19

please introduce const for 19

**Comment by dmitri-baklan** [comment]
Those values was setted to "renguBoardWidth" and "renguBoardHeight" variables.
