### ISSUE TITLE
Conditions nesting

### ISSUE THREAD

**Issue by Zak-Roz** [dmitri-baklan/MIPZ#5]
Better to avoid nesting

https://github.com/dmitri-baklan/MIPZ/blob/main/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L42
https://github.com/dmitri-baklan/MIPZ/blob/main/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L57
https://github.com/dmitri-baklan/MIPZ/blob/main/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L72
https://github.com/dmitri-baklan/MIPZ/blob/main/RenjuChecker/src/main/java/org/example/service/RenjuWinChecker.java#L85

**Comment by dmitri-baklan** [comment]
Conditions simplified and removed to external methods.
